### ISSUE TITLE
pip 3.5 broken

### ISSUE THREAD

**Issue by kootenpv** [awkman/pywifi#2]
After `pip3.5 install pywifi`

```
>>> import pywifi
>>> pywifi.PyWiFi()
AttributeError: module 'pywifi' has no attribute 'PyWiFi'
```

**Comment by fuzzy-focus** [comment]
Publishing your current version of this repo to PyPI would fix it.

The broken imports (´´´import win.interfaces´´´) are the issue.

**Comment by awkman** [comment]
Thanks for you help. I already published current version onto PyPI and do some basic tests under Ubuntu environment. The issue disappeared.

**Comment by kootenpv** [comment]
Cool, that helped!
