### ISSUE TITLE
iface.connect(profile) always return const.IFACE_DISCONNECTED win10 python3

### ISSUE THREAD

**Issue by WuQio** [awkman/pywifi#22]
iface.connect(profile) always return const.IFACE_DISCONNECTED. I use Python3, win10. It cannot connect to my AP even if the key is write.

`
from pywifi import *
import time

def main():
    wifi = PyWiFi()
    iface = wifi.interfaces()[0]
    iface.scan()
    time.sleep(1)
    scanres = iface.scan_results()

    profile = Profile()

    for s in scanres:
        if s.ssid == 'meilan':
            profile.ssid = s.ssid
            profile.auth = s.auth
            profile.akm.append(s.akm[0])
            profile.cipher = s.cipher
            break
    key = 'abcdefgg'
    profile.key = key
    profile = iface.add_network_profile(profile)
    iface.remove_all_network_profiles()
    iface.connect(profile)
    time.sleep(30)
    print(iface.status())

main()
`

**Comment by awkman** [comment]
@WuQio Remove the line "iface.remove_all_network_profiles()" to try whether your code could work properly

**Comment by RealSniperKing** [comment]
I have a same problem, yet I not the line "iface.remove_all_network_profiles()" -_-
My OS : Windows 10
My python : 3.6.2
What is there a solution for this bug ?
