### ISSUE TITLE
打扰了，为什么采用ssh模式在树莓派里运行程序时，报错说产生了一个iface的临时文件没有权限访问？

### ISSUE THREAD

**Issue by IWantFight** [awkman/pywifi#33]

**Comment by awkman** [comment]
Could you share the detail log? May be you need to change to root permission to run the code?!

**Comment by IWantFight** [comment]
当我把ifaces = wifi.interfaces()[0]改为ifaces = wifi.interfaces()[1]后，在树莓派里可以正常运行了，不知道是为啥。
