### ISSUE TITLE
NameError: name 'const' is not defined

### ISSUE THREAD

**Issue by qqkl662** [awkman/pywifi#39]
when I run the example,I meet this questions.(win10 python3.6.6).
I also meet similar error in envionment(win10 python 3.5.5)
![question](https://user-images.githubusercontent.com/42534003/49442694-3efb9480-f805-11e8-87fb-1f8a56e28994.jpg)

**Comment by oycillessen** [comment]
You should use "pywifi.const" instead of "const".

**Comment by qqkl662** [comment]
> You should use "pywifi.const" instead of "const".

thank you for your reply,
