### ISSUE TITLE
Does it support for mutil wifi wlan card

### ISSUE THREAD

**Issue by E666GT** [awkman/pywifi#42]
I have two wifi device.
One in my computer is "Qualcomm Atheros AR9285 Wireless Netword Adapter"
Another is "802.11n USB Wireless LAN Card"

I can use either of them to connect wifi for Internet.
BUT, I use
`ifacelist=pywifi.PyWiFi().interfaces()`
**in this list, I can only get one iface.** Sometimes it is the first device, sometimes it is the second device. This confussed me, How could I get both of them?

**Comment by E666GT** [comment]
by the way i'm using windows and python 365

**Comment by awkman** [comment]
I fixed this issue in https://github.com/awkman/pywifi/commit/5a4a2e2fb36c5575120152186800065b84ed2b36

**Comment by E666GT** [comment]
Thanks for your work. This lib helps me a lot in my newly school project.
