### ISSUE TITLE
NotImplementedError in MacOSX10.15

### ISSUE THREAD

**Issue by Rhythmicc** [awkman/pywifi#52]
```shell
➜ ~ $ pip3 install pywifi
Collecting pywifi
  Downloading https://files.pythonhosted.org/packages/89/55/170a52685eeefeab36bfaf26bdca629263a0a28efffc3b556b2cc86ab966/pywifi-1.1.12-py3-none-any.whl
Installing collected packages: pywifi
Successfully installed pywifi-1.1.12
You are using pip version 19.0.3, however version 19.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
➜ ~ $ python3 
Python 3.7.4 (v3.7.4:e09359112e, Jul  8 2019, 14:54:52) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pywifi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pywifi/__init__.py", line 15, in <module>
    from .wifi import PyWiFi
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pywifi/wifi.py", line 15, in <module>
    from .iface import Interface
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pywifi/iface.py", line 15, in <module>
    raise NotImplementedError
NotImplementedError
>>> exit()
```

**Comment by kaiwenzhou2000** [comment]
it seems like pywifi only support win or linux, and pywifi also can not run in my macbook

**Comment by SylarCao** [comment]
> it seems like pywifi only support win or linux, and pywifi also can not run in my macbook

我也遇到了相同的问题

**Comment by chankeh** [comment]
same to me,how  to solve the problem

**Comment by Rhythmicc** [comment]
> same to me,how to solve the problem

write a fake class to replace pywifi. (using `os.system()`)

**Comment by magbone** [comment]
https://github.com/awkman/pywifi/blob/719baf73d8d32c623dbaf5e9de5d973face152a4/pywifi/iface.py#L15 The 10th to 15th  line of ```ifcace.py``` file tells that the ```pywifi``` only supports Windows and Linux platform but in MacOS it doesn't implement.

**Comment by pullukse** [comment]
aghhhhh why exclude mac peeps :'(((

**Comment by we1x4n** [comment]
直接`pip install pywifi`中的iface.py文件在导包的时候判断系统是没有Mac OS X
```
pip3 uninstall pywifi
git clone -b macos_dev https://github.com/awkman/pywifi
cd pywifi
pip3 install .
```
在进行`import pywifi`就不会报`NotImplementedError`了

**Comment by Rhythmicc** [comment]
thanks!

**Comment by SStarrySSky** [comment]
> 直接`pip install pywifi`中的iface.py文件在导包的时候判断系统是没有Mac OS X
> 
> ```
> pip3 uninstall pywifi
> git clone -b macos_dev https://github.com/awkman/pywifi
> cd pywifi
> pip3 install .
> ```
> 
> 在进行`import pywifi`就不会报`NotImplementedError`了

it turned out that ERROR: You must give at least one requirement to install (see "pip help install")

**Comment by SwayingWheatfield** [comment]
> 直接`pip install pywifi`中的iface.py文件在导包的时候判断系统是没有Mac OS X
> 
> ```
> pip3 uninstall pywifi
> git clone -b macos_dev https://github.com/awkman/pywifi
> cd pywifi
> pip3 install .
> ```
> 
> 在进行`import pywifi`就不会报`NotImplementedError`了

ERROR: Directory '.' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.
