### ISSUE TITLE
Basic functions with PyWiFi.intefaces not working. (Python 2.7.12 - Win 10)

### ISSUE THREAD

**Issue by chibill** [awkman/pywifi#8]
I am on Windows10 with python 2.7.12

`>>> wifi.interfaces()[0].scan()
>>> wifi.interfaces()[0].scan_results
<bound method Interface.scan_results of <pywifi.iface.Interface instance at 0x0313CAF8>>
>>> wifi.interfaces()[0].scan_results()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\pywifi\iface.py", line 39, in scan_results
    return wifiutils.scan_results(self.__raw_obj)
  File "C:\Python27\lib\site-packages\pywifi\win\wifiutils.py", line 30, in scan_results
    network['ssid'] += "%c" % bsses[i].dot11Ssid.ucSSID[j]
IndexError: string index out of range
>>> wifi.interfaces()[0].status
<bound method Interface.status of <pywifi.iface.Interface instance at 0x0313CAF8>>
>>> wifi.interfaces()[0].status()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\pywifi\iface.py", line 74, in status
    return wifiutils.status(self.__raw_obj)
  File "C:\Python27\lib\site-packages\pywifi\win\wifiutils.py", line 186, in status
    data = wifiapi.PDWORD()
AttributeError: 'module' object has no attribute 'PDWORD'`

is the error.

**Comment by awkman** [comment]
Did you try running pywifi in python3 env? Because I wrote pywifi in python3 env, I am not quite sure it can run on python2 env now

**Comment by chibill** [comment]
Well.. I was using py2

**Comment by chibill** [comment]
I'm mostly use py2 because that's what most people use. (Like even most
professionals use it over py3)

**Comment by chibill** [comment]
Any idea if this can be looked into?

**Comment by awkman** [comment]
After I fix issue #10, I will try to test pywifi under py2.7 and evaluate is it possible to support py2.7. I am not quite sure about how many py3 features now pywifi depends on...

**Comment by thepizzagui** [comment]
I think what needs to be considered is the way python 2.7 handles imports compared to python 3.X as well as some syntax changes. Might not even be worth going to 2.7 as the differences between the two are quite large. 

Heres a handy little article: 
[http://sebastianraschka.com/Articles/2014_python_2_3_key_diff.html](url)

**Comment by chibill** [comment]
So should I just continue searching for a py2.7 compatible wifi lib and just close this? Because I need to stay on 2.7 (I have many reasons)

**Comment by thepizzagui** [comment]
Up to awkman I suppose, whats your aim with the use of this lib?

**Comment by chibill** [comment]
Well I am mostly interested in being able to get the wifi BSSID around me. So I can make a script to auto connect to some APs. (Like the free ones at McDonalds.)

**Comment by thepizzagui** [comment]
Im working on something similar as a small project. At its current version the code I linked is quite messy however it gets bssids and ssids and stores then in a dict for easy access. Probably works for 2.7

**Comment by chibill** [comment]
I can make the current version ( Just now downloaded from repo) load and work by just changing the way that the metaclass is defined.. (Do it the python 2 why that is still correct for python 3).

And it appears to work. (Scan works and scan_results works. Still testing other stuff)

**Comment by chibill** [comment]
Okay the network_profiles works (Sort of one of the networks around me has a key type that errors it out. WPA2) I also know how to patch it so that status works (Python 2.7 ctypes.wintypes does not have PDWORD but if you copy the line that defines it from cytpes.wintypes on python 3 it works)

**Comment by awkman** [comment]
@chibill Good news!! Is it convenient for you to send a PR after you finish the modification and test under python 2.7? I would learn from the patch and try to merge it into pywifi!!

**Comment by chibill** [comment]
I can.  Not sure about the strange stuff with WPA2 it seems odd. (But that exists in. Python3)

**Comment by chibill** [comment]
I mean the problem with that exists in py3 also

**Comment by awkman** [comment]
Could you share the error message?

**Comment by chibill** [comment]
I know why its erroring.   https://github.com/awkman/pywifi/blob/master/pywifi/win/wifiutil.py#L43-L47 Does not contain a value with the key WPA2 (Which is the auth type my schools wifi uses when looking at the xml file)

**Comment by awkman** [comment]
Oh... I don't start to plan to support other key mgmt type now. That's because I don't have the environment to test them. I think we should add one more key mgmt type like 'OTHER' to skip it.

**Comment by chibill** [comment]
True..  I wonder how you could handle them. (Why do you use a dict there anyways?)

**Comment by awkman** [comment]
I didn't consider other auth type at that moment, so I adopted dist here.
I want a unified expression for key mgmt while getting the scan result or assigning the ap profile.
So, I think keep them as integers is better.

**Comment by chibill** [comment]
Okay. Currently they are only used for network_profiles. And adapting them to use the string directly actually removes so if statements from the add_network_profile. (Would only need to check for if its open)

I will leave that alone as I am just interested in getting it python 2 compatible.

**Comment by awkman** [comment]
@chibill  Thanks for your idea and PR, I merge your PR now.

**Comment by chibill** [comment]
Okay. So this can be closed now. :)
